resources:
  - ../../../base/postgres
  - secrets.yaml
  - config.yaml

images:
  - name: docker.io/library/postgres:<patched>
    newTag: 17.7@sha256:1c2b6ae7bd9b9a334a956ea3b6fb9681351991e68fc1d6e8d3c6aa94fc43254a
