resources:
  - ../../../base/influxdb
  - secrets.yaml

images:
  - name: docker.io/library/influxdb:<patched>
    newTag: 2.8.0@sha256:47d5ee97ca868e0d669db8ec37bdb72373d11a1fdd16e6ee712447a865d4d119
