apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
    name: influxdb
    namespace: grayc-inoa-qas
    labels:
        grafana-instance: grafana-inoa-qas
spec:
    instanceSelector:
        matchLabels:
            grafana-instance: grafana-inoa-qas
    datasource:
        name: ENC[AES256_GCM,data:3pX2bkWMuj8=,iv:3ugPgnysI7zRsOeV+uHE3x+nPZ7PtSnGiamEp+FWPY4=,tag:DTYbWRX+Gg8DakFuXxCWRg==,type:str]
        type: ENC[AES256_GCM,data:CK15QvbxUWw=,iv:xxymdNe7E4tBoDnSiMtTPwSab2lMd35V4qIISj2UjVU=,tag:6f/A4kWRYP9ABSmFIt3+Mg==,type:str]
        url: ENC[AES256_GCM,data:T4+Z/14RwMTR6YINTBIlr6VbGqiR,iv:5WyK77zTym+XILtl4lYbWyqVgpWQ9wkgAk3BOps0fbk=,tag:FKzQ6intlxegZXmj3Q8PLA==,type:str]
        access: ENC[AES256_GCM,data:zbDlTqU=,iv:qFsgK3O7pq+R6QohndHPK6StCEXHq2lxQnjvoibAJfw=,tag:tDR1hsKFS8Pjhx2DEQk/CQ==,type:str]
        isDefault: ENC[AES256_GCM,data:kt3AWA==,iv:Yk9/J0pl5Msv4gYKu/iAY7fqNyUGZJfNwB+96GbFk8s=,tag:9+J9wBgsK49yiL7P06JVEA==,type:bool]
        editable: ENC[AES256_GCM,data:NmOKzA==,iv:nL4WhSr5W3RIkORiHOodCm/gffH2+cB2701x+0nnqpw=,tag:hQCosJMt6pXgx3LlbsqPaw==,type:bool]
        jsonData:
            version: ENC[AES256_GCM,data:RxMMGw==,iv:7XJlbJBUt2GIhzM37reS9mqNFxp+3rtsWGSC7aOngTE=,tag:Rb91Y8Jf2Vp3x2jVP03yUQ==,type:str]
            organization: ENC[AES256_GCM,data:99xoXA==,iv:+HNOSPaLUuHb4s5JQYXr+LHLCKWn+siEkXhwWzRT6T0=,tag:YQp624sXKMk2L/Ov4b+/jQ==,type:str]
            defaultBucket: ENC[AES256_GCM,data:kaXI4Q==,iv:fKXB9nGzAfZFmFC5IrRQno7OqHvw7PDBFaVgEwHeUrc=,tag:0AOFcr5zZ4PY3AheGbjuSw==,type:str]
        secureJsonData:
            token: ENC[AES256_GCM,data:CugLVfGN/02M4HK1/YFPBVSSOw8cstPXgX6r6otwpp2QSdRYA53s3z7Rq8CBzvA0dPF+6xy0xL/X3JCRNva+IqCBEYt8dvZ9z90sacfRhbEhSgCe6pC0AQ==,iv:X+dNFWjt6m9BUYpDhJg7rFZllmsjlUrwI/ims0FkMvs=,tag:zV/NXpQJG7pCAb7roNhvIQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
          created_at: "2025-11-27T15:50:06Z"
          enc: CiQAIt230JkXetALE2T55p9Vt++d+HA/VjRZb3KYWqajBBMnPhkSSQD2lEBUoc2nalwnfA22niTyNX4kLsZVPjJYsdjoP+VR6CowT7K8o5f++ak/3X0KJMtz++nHpHJjw3Mx9yCn9azK1NDZ7fzFb+c=
    lastmodified: "2025-11-27T15:50:07Z"
    mac: ENC[AES256_GCM,data:gB1VdW7Omeimc5vLacjIBRhxe1x00BPDVFZILZdAoA5BkQ79tOobdsNQiiJq3rkfLIRKCiPZGkyG32va7eNHfOZyU0CZ+w6XcF2wRKcAKyR5xcszXPsLNcTJL1XgXV52ezRrP6cmcOtjoLDO0L5NgkAeVlbWwtxfMGkGmhHtmR8=,iv:jXKytRN3NH2v/LzrybqthAIkhhyDBbU0wFMoVWhfIjc=,tag:/xg/c1Y8aoRof8v9Vrrx2Q==,type:str]
    encrypted_regex: ^(datasource)$
    version: 3.10.0
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
    name: postgres
    namespace: grayc-inoa-qas
    labels:
        grafana-instance: grafana-inoa-qas
spec:
    instanceSelector:
        matchLabels:
            grafana-instance: grafana-inoa-qas
    datasource:
        name: ENC[AES256_GCM,data:1BokSvchK50=,iv:hk3kEvBmY4Z+O02OHwopUVC5YfE+l9TTzsNwwDKA05I=,tag:NBJ5poiPtcDU3RUZsdbfbw==,type:str]
        type: ENC[AES256_GCM,data:yL9+J7NwgJ40q2zaQFna2Qyg6lI29K79u+uLJDo=,iv:Pgr8mVNDtHVQ1TWUgx19jhXq5nN+2oILU7GuBYZA+4c=,tag:34UEtvxwywbf2qwybYzy1g==,type:str]
        url: ENC[AES256_GCM,data:z5SKnzwgLN6ecDPaOw==,iv:buSIYa3UaQE6SZ3NCH3PWfakQQRrjvYEvVWBCdYc/aY=,tag:A1+/dazrPdzQQiLZpAGzoA==,type:str]
        access: ENC[AES256_GCM,data:VEtjWVw=,iv:PRMm18juYSOM0eAepCLN7ujm792Q6THZwFlFDxqwOJQ=,tag:+Y9debcbpXDfSzdSYeOTdw==,type:str]
        user: ENC[AES256_GCM,data:bbTKwg==,iv:3otDSHcttxv/dEUhNzZVOedwnY+4SDzb6kDFaRx2Gc4=,tag:yJ8K1jfR+YyvLO9lByKDlQ==,type:str]
        jsonData:
            database: ENC[AES256_GCM,data:VR8flQ==,iv:iH7HdvhtpshZe4glL8r5EtVs4YKYWxlyd9/U9f9osYU=,tag:4uZLYdQ9aExKHdNRmQiQMw==,type:str]
            sslmode: ENC[AES256_GCM,data:do+66ngglQ==,iv:nAITACQlaI9UXRSaF3d35zCJWESrJs3Ot6sByMjc4pA=,tag:hUCBYXyG/FPYfN+A/4HeiQ==,type:str]
        secureJsonData:
            password: ENC[AES256_GCM,data:Y8c8RckqOb0xlvNDHtpBZD72v1nSlQ==,iv:I5tiioe764hUbbTvCpZs8vetRff//9YkW2/29XsRHAo=,tag:DpNfIcC7+jLMSn1Z8sNpDQ==,type:str]
        isDefault: ENC[AES256_GCM,data:Xua+NUg=,iv:mD/Aft8kJYu4hkaTOKof5j6pb7qO+fD3kx/TR93Tcm8=,tag:XLG3a4tt9E5fdOmFAcPbuQ==,type:bool]
        editable: ENC[AES256_GCM,data:C+fbkA==,iv:Tfpm65GHqqW5wMSHMh3HX5jI2u0pt3MLEt/S+4ujljo=,tag:yPmhg7NgxunlF8V8qdO3ug==,type:bool]
sops:
    gcp_kms:
        - resource_id: projects/grayc-infrastructure/locations/europe/keyRings/sops/cryptoKeys/fluxcd
          created_at: "2025-11-27T15:50:06Z"
          enc: CiQAIt230JkXetALE2T55p9Vt++d+HA/VjRZb3KYWqajBBMnPhkSSQD2lEBUoc2nalwnfA22niTyNX4kLsZVPjJYsdjoP+VR6CowT7K8o5f++ak/3X0KJMtz++nHpHJjw3Mx9yCn9azK1NDZ7fzFb+c=
    lastmodified: "2025-11-27T15:50:07Z"
    mac: ENC[AES256_GCM,data:gB1VdW7Omeimc5vLacjIBRhxe1x00BPDVFZILZdAoA5BkQ79tOobdsNQiiJq3rkfLIRKCiPZGkyG32va7eNHfOZyU0CZ+w6XcF2wRKcAKyR5xcszXPsLNcTJL1XgXV52ezRrP6cmcOtjoLDO0L5NgkAeVlbWwtxfMGkGmhHtmR8=,iv:jXKytRN3NH2v/LzrybqthAIkhhyDBbU0wFMoVWhfIjc=,tag:/xg/c1Y8aoRof8v9Vrrx2Q==,type:str]
    encrypted_regex: ^(datasource)$
    version: 3.10.0
